feat: add IP Address Field
Normal-OJ/new-front-end pull request #149
Opened 2023-11-04 21:21 UTC by aokblast

This patch add IPAddress Field on Submission Pages as BackEnd have this change.

2023-11-05 00:17 UTC, uier commented
Hi @aokblast, the changes look good to me, only one question, does the IP Address need to be displayed for every users?

Or it's mainly for TA & instructor? In this case, it would be better to only show the IP Address for admin users by adding `v-if="session.isAdmin"` on `<td>` and `<th>`. Because the table has too many columns and seems clutter.

2023-11-05 00:21 UTC, uier commented
oh, another question, you may also wanna add this ip column in `src/pages/course/[name]/submissions/[id].vue`? This page component is used for page displaying single submission details.

2023-11-06 12:57 UTC, uier requested changes

2023-11-06 13:26 UTC, aokblast commented on src/pages/course/[name]/submission/[id].vue
> +                  <th>{{ $t("course.submission.detail.ipAddr") }}</th>
Fix it

2023-11-06 13:28 UTC, uier approved these changes
Thanks!

2023-11-06 14:17 UTC, merged