feat: add mobile problem card
Normal-OJ/new-front-end pull request #161
Opened 2024-01-06 17:03 UTC by laporchen

close #160

2025-05-10 06:57 UTC, uier commented
left is admin, right is student

Tablet view:
![image](https://github.com/user-attachments/assets/cb1d8cc6-395c-4ada-bb10-1f02a6802b67)

Mobile view, 
<div class="display: flex">
<img width="250px" src="https://github.com/user-attachments/assets/4842bc1a-469d-4be7-95b8-6ee49ded7a06">
<img width="250px" src="https://github.com/user-attachments/assets/32c1213d-588b-4f7b-aa30-4301c1d676f4">
</div>

2025-05-10 07:35 UTC, uier approved these changes

2025-05-10 07:36 UTC, uier requested changes

2025-05-10 07:36 UTC, uier commented on src/components/Problem/ProblemInfo.vue
> +            {{ visible === 0 ? "Public" : "Hidden" }}
`visible === ProblemStatus.Visible`

2025-05-10 07:43 UTC, uier commented
@laporchen Thanks for the mobile view! please help resolve a simple conflicts, and a tiny coding style

2025-05-10 08:35 UTC, uier commented
let me do this.

2025-05-10 08:50 UTC, uier commented
As I also author a change in this PR, set @Bogay as reviewer to help.

Hi Bogay, I'm curious the `declare enum` usage in *.d.ts file, I though the template could directly use it but seems not. I change to `export enum` to make it importable to the template to use for a condition check. What do you think.

If `declare enum` should be replaced by `export enum`, then we need another issue to request chaning all `delcare enum` usage in the codebase (actually only in submission.d.ts)

2025-05-10 09:00 UTC, Bogay commented
I think we should use `export` and move those declaration to `.ts` instead of `.d.ts`

2025-05-10 09:04 UTC, uier commented
@Bogay agree, I'm temporarily adding PROBLEM_STATUS in constants.ts just like SUBMISSION_STATUS.
Let's put the .d.ts thing as a new issue to deal with

2025-05-10 09:08 UTC, Bogay approved these changes
👍

2025-05-11 13:45 UTC, uier approved these changes

2025-05-11 13:45 UTC, merged