Homework Create/Edit/Delete
Normal-OJ/new-front-end pull request #27
Opened 2023-01-07 16:15 UTC by uier

2023-01-07 18:59 UTC, Bogay commented
這應該是針對公告而非作業的 PR？

2023-01-07 19:08 UTC, Bogay requested changes

2023-01-07 19:08 UTC, Bogay commented on src/pages/announcements/[id].vue
> +} = useAxios<AnnouncementList>(`/ann/${route.params.id}`, fetcher);
課程公告的 route 是 `/ann/<course_name>/<ann_id>`，去掉 `course_name` 的話會拿到系統公告

2023-01-07 19:08 UTC, Bogay commented on src/pages/course/[name]/announcements/[id]/edit.vue
> +} = useAxios<AnnouncementList>(`/ann/${route.params.id}`, fetcher);
或許這邊要放進 `models`？提供統一介面

2023-01-07 20:15 UTC, uier commented on src/pages/announcements/[id].vue
> +} = useAxios<AnnouncementList>(`/ann/${route.params.id}`, fetcher);
`src/pages/announcements/[id].vue` 是展示系統公告沒錯
`src/pages/course/[name]/announcements/[id].vue` 才是課程公告

2023-01-07 20:16 UTC, uier commented on src/pages/course/[name]/announcements/[id]/edit.vue
> +} = useAxios<AnnouncementList>(`/ann/${route.params.id}`, fetcher);
之後跟 namespace 一起修吧，是說這邊要統一介面是不是必須要用 composable 阿 🤔

2023-01-08 06:02 UTC, Bogay approved these changes

2023-01-08 06:02 UTC, merged